name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Compile and link
      run: |
        aarch64-linux-android${{ matrix.arch }}-clang++ \
          -static-libstdc++ -w -Wno-c++11-narrowing -DUSE_STANDALONE \
          -o poc poc.cpp -llog
