name: Build for aarch64-linux-android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [aarch64-linux-androidXX]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Clang and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang

      - name: Compile and link
        run: |
          aarch64-linux-android${{ matrix.arch }}-clang++ \
            -static-libstdc++ -w -Wno-c++11-narrowing -DUSE_STANDALONE \
            -o poc poc.cpp -llog
